name: Check PR 

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    name: Build & test
    permissions: 
      checks: write
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: TestProject/Library
          key: Library-${{ hashFiles('TestProject/Assets/**', 'TestProject/Packages/**', 'TestProject/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Check out action
        uses: actions/checkout@v4
        with:
          repository: meticalabs/unity-test-runner
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: ./.github/actions/unity-test-runner
          
      - name: Run tests
        uses: ./.github/actions/unity-test-runner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          E2E_TESTSAPP_API_KEY: ${{ secrets.E2E_TESTSAPP_API_KEY }}
          ODS_ENDPOINT: ${{ secrets.ODS_ENDPOINT }}
          
        with:
          projectPath: TestProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}

